# Generated by Django 4.2.7 on 2023-12-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='orderd',
            new_name='ordered',
        ),
    ]
